# Generated by Django 4.0.6 on 2022-07-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_id',
            field=models.CharField(blank=True, default='user_id', max_length=40, verbose_name='유저아이디'),
        ),
    ]
